### ISSUE TITLE
Cannot cluster text units

### ISSUE THREAD

**Issue by gemmell** [LexPredict/lexpredict-contraxsuite#11]
The "cluster by" field is somewhat broken. I think it's supposed to be a drop down, instead it's a text field.
image

![image](https://user-images.githubusercontent.com/3324817/30857895-e38bc728-a300-11e7-878b-953140be35d5.png)

Even if I type "terms" into that it doesn't work.

**Comment by mjbommar** [comment]
@gemmell , based on your notes/issues, your jq and canvas installations are broken.  We have seen a similar issue when clients run the script as root or copy files to the wrong paths.  Can you enable the Developer Console and share the log when you load the page?  

See sample image below for expected behavior.
![image](https://user-images.githubusercontent.com/85053/30858493-e75e632e-a28d-11e7-891b-ea6f993f55a0.png)

It may be simpler for you to wait for 1.0.2 release to do a clean install, as it can be difficult to "undo" some of the steps when the script was originally run as root.
