### ISSUE TITLE
Task list now empty

### ISSUE THREAD

**Issue by dwmcqueen** [LexPredict/lexpredict-contraxsuite#24]
This may have been a slight stress test, but after loading the documents, I did the following:

1. Document->Text Units->Text Unit List
2.  Filtered on "liability" and then found a limitation of liability clause
3.  Classify Text Unit - > Class Name = "Limitation of Liability" and Class Value = "limitation" (the documentation doesn't state the significance of these variables so I was guessing)
4.  Admin Tasks - > Analyze - > Classify Text Unit (selecting "Limitation of Liability")

The task errored out (as it should) with a "ValueError: Cannot have number of splits n_splits=3 greater than number of samples: 1"

However, now the admin task list is empty.  When I add a new task (which runs per celery.log), the admin task list remains empty.

**Comment by reddalexx** [comment]
There was broken link related with task results.
fixed here: https://github.com/LexPredict/lexpredict-contraxsuite/commit/13ca903c62b27fa482f4fc14ea8a32879ed77ced

In order to repair admin task list - run "Clean Task List" admin task, it will delete 
all tasks with "Success" and "Failure" status, and you will be able 
to re-run Classification task and see results.
